import { delay } from '@/utils/delay'
import type { Book, BookSearchParams } from '@/types/book'

// 백엔드 연동 전까지 mock 데이터를 사용합니다. 실 연동 시 이 파일을 axios 호출로 교체하세요.
const MOCK_BOOKS: Book[] = [
  {
    id: 'book-01',
    title: '박곰희 연금 부자 수업',
    author: '박곰희',
    publisher: '인플루엔셜',
    category: '자기계발',
    price: 21000,
    discountRate: 10,
    rating: 9.7,
    reviewCount: 523,
    stock: 120,
    status: 'ON_SALE',
    publishedAt: '2026-07-20',
    updatedAt: '2026-08-01',
  },
  {
    id: 'book-02',
    title: '안녕이라 그랬어 (집 에디션)',
    author: '김애란',
    publisher: '문학동네',
    category: '소설',
    price: 16800,
    discountRate: 10,
    rating: 9.6,
    reviewCount: 604,
    stock: 85,
    status: 'ON_SALE',
    publishedAt: '2025-09-15',
    updatedAt: '2026-07-28',
  },
  {
    id: 'book-03',
    title: '모순',
    author: '양귀자',
    publisher: '쓰다',
    category: '소설',
    price: 13000,
    discountRate: 10,
    rating: 9.6,
    reviewCount: 2149,
    stock: 200,
    status: 'ON_SALE',
    publishedAt: '2024-05-20',
    updatedAt: '2026-07-20',
  },
  {
    id: 'book-04',
    title: '위버멘쉬',
    author: '프리드리히 니체',
    publisher: '떠오름',
    category: '인문',
    price: 17800,
    discountRate: 10,
    rating: 9.1,
    reviewCount: 649,
    stock: 60,
    status: 'ON_SALE',
    publishedAt: '2025-02-10',
    updatedAt: '2026-06-30',
  },
  {
    id: 'book-05',
    title: '혼모노 (리커버)',
    author: '성해나',
    publisher: '창비',
    category: '소설',
    price: 18000,
    discountRate: 10,
    rating: 9.1,
    reviewCount: 919,
    stock: 0,
    status: 'OUT_OF_STOCK',
    publishedAt: '2024-08-12',
    updatedAt: '2026-08-05',
  },
  {
    id: 'book-06',
    title: '싯다르타',
    author: '헤르만 헤세',
    publisher: '민음사',
    category: '소설',
    price: 8000,
    discountRate: 10,
    rating: 9.5,
    reviewCount: 835,
    stock: 300,
    status: 'ON_SALE',
    publishedAt: '2002-05-01',
    updatedAt: '2026-06-10',
  },
  {
    id: 'book-07',
    title: '어른의 행복은 조용하다',
    author: '태수',
    publisher: '페이지2북스',
    category: '에세이',
    price: 17800,
    discountRate: 10,
    rating: 9.5,
    reviewCount: 535,
    stock: 45,
    status: 'ON_SALE',
    publishedAt: '2024-01-15',
    updatedAt: '2026-07-11',
  },
  {
    id: 'book-08',
    title: '자몽살구클럽',
    author: '한로로',
    publisher: '어센틱',
    category: '에세이',
    price: 12000,
    discountRate: 10,
    rating: 9.1,
    reviewCount: 332,
    stock: 15,
    status: 'ON_SALE',
    publishedAt: '2025-12-01',
    updatedAt: '2026-08-10',
  },
  {
    id: 'book-09',
    title: '불편한 편의점',
    author: '김호연',
    publisher: '나무옆의자',
    category: '소설',
    price: 14000,
    discountRate: 10,
    rating: 9.3,
    reviewCount: 12500,
    stock: 500,
    status: 'ON_SALE',
    publishedAt: '2021-04-20',
    updatedAt: '2026-05-18',
  },
  {
    id: 'book-10',
    title: '미움받을 용기',
    author: '기시미 이치로',
    publisher: '인플루엔셜',
    category: '인문',
    price: 16500,
    discountRate: 10,
    rating: 9.4,
    reviewCount: 8300,
    stock: 220,
    status: 'ON_SALE',
    publishedAt: '2014-11-17',
    updatedAt: '2026-04-22',
  },
  {
    id: 'book-11',
    title: '데미안',
    author: '헤르만 헤세',
    publisher: '민음사',
    category: '소설',
    price: 9800,
    discountRate: 10,
    rating: 9.3,
    reviewCount: 4210,
    stock: 0,
    status: 'DISCONTINUED',
    publishedAt: '2000-03-01',
    updatedAt: '2026-03-02',
  },
  {
    id: 'book-12',
    title: '아몬드',
    author: '손원평',
    publisher: '창비',
    category: '소설',
    price: 13800,
    discountRate: 10,
    rating: 9.5,
    reviewCount: 6200,
    stock: 150,
    status: 'ON_SALE',
    publishedAt: '2017-06-30',
    updatedAt: '2026-07-01',
  },
  {
    id: 'book-13',
    title: '죽고 싶지만 떡볶이는 먹고 싶어',
    author: '백세희',
    publisher: '흔',
    category: '에세이',
    price: 13800,
    discountRate: 10,
    rating: 9.0,
    reviewCount: 3100,
    stock: 80,
    status: 'ON_SALE',
    publishedAt: '2018-01-10',
    updatedAt: '2026-02-14',
  },
  {
    id: 'book-14',
    title: '트렌드 코리아 2026',
    author: '김난도',
    publisher: '미래의창',
    category: '경제경영',
    price: 19800,
    discountRate: 10,
    rating: 8.9,
    reviewCount: 1200,
    stock: 300,
    status: 'ON_SALE',
    publishedAt: '2025-10-25',
    updatedAt: '2026-08-12',
  },
  {
    id: 'book-15',
    title: '세이노의 가르침',
    author: '세이노',
    publisher: '데이원',
    category: '자기계발',
    price: 16000,
    discountRate: 10,
    rating: 9.2,
    reviewCount: 9800,
    stock: 400,
    status: 'ON_SALE',
    publishedAt: '2023-03-15',
    updatedAt: '2026-06-05',
  },
  {
    id: 'book-16',
    title: '나미야 잡화점의 기적',
    author: '히가시노 게이고',
    publisher: '현대문학',
    category: '소설',
    price: 15800,
    discountRate: 10,
    rating: 9.6,
    reviewCount: 7400,
    stock: 180,
    status: 'ON_SALE',
    publishedAt: '2012-09-18',
    updatedAt: '2026-05-30',
  },
  {
    id: 'book-17',
    title: '사피엔스',
    author: '유발 하라리',
    publisher: '김영사',
    category: '인문',
    price: 22000,
    discountRate: 10,
    rating: 9.4,
    reviewCount: 5600,
    stock: 90,
    status: 'ON_SALE',
    publishedAt: '2015-11-24',
    updatedAt: '2026-04-09',
  },
  {
    id: 'book-18',
    title: '코스모스',
    author: '칼 세이건',
    publisher: '사이언스북스',
    category: '과학',
    price: 24000,
    discountRate: 10,
    rating: 9.5,
    reviewCount: 3200,
    stock: 40,
    status: 'ON_SALE',
    publishedAt: '2006-12-08',
    updatedAt: '2026-01-20',
  },
  {
    id: 'book-19',
    title: '지구 끝의 온실',
    author: '김초엽',
    publisher: '자이언트북스',
    category: '소설',
    price: 15000,
    discountRate: 10,
    rating: 9.1,
    reviewCount: 2100,
    stock: 0,
    status: 'OUT_OF_STOCK',
    publishedAt: '2021-08-25',
    updatedAt: '2026-07-15',
  },
  {
    id: 'book-20',
    title: '흔들리며 피는 꽃',
    author: '도종환',
    publisher: '문학동네',
    category: '시',
    price: 9000,
    discountRate: 10,
    rating: 8.8,
    reviewCount: 1500,
    stock: 60,
    status: 'ON_SALE',
    publishedAt: '2020-04-01',
    updatedAt: '2026-03-19',
  },
]

export async function fetchBooks(params: BookSearchParams): Promise<Book[]> {
  const keyword = params.keyword.trim().toLowerCase()
  const filtered = MOCK_BOOKS.filter((book) => {
    const matchesKeyword =
      keyword === '' ||
      book.title.toLowerCase().includes(keyword) ||
      book.author.toLowerCase().includes(keyword)
    const matchesCategory = params.category === 'ALL' || book.category === params.category
    const matchesStatus = params.status === 'ALL' || book.status === params.status
    return matchesKeyword && matchesCategory && matchesStatus
  })
  return delay(filtered)
}
