-- 역할 관리 메뉴 부여 트리 24건 (부모가 자식보다 먼저 오도록 순서 유지)
INSERT INTO `program` (`id`, `parent_id`, `label`, `code`, `type`)
VALUES ('test-misc', NULL, '테스트', 'TESET_III', 'PAGE'),
       ('genx-menu1', NULL, 'GENX 관리자 메뉴1(GENX 시스템 내)', 'GENX_TEST3', 'PAGE'),
       ('project-list', NULL, '프로젝트', 'PROJECT_LIST', 'PAGE'),
       ('project-detail', NULL, '프로젝트 상세', 'PROJECT_DETAIL', 'PAGE'),
       ('project-detail-task-list', 'project-detail', '프로젝트 상세 조회 (Task 리스트)', 'PROJECT_DETAIL_API_R', 'API'),
       ('project-detail-project', 'project-detail', '프로젝트 상세 (프로젝트)', 'PROJECT_DETAIL_PROJECT_API', 'API'),
       ('step-list', 'project-detail', 'Step List 조회', 'STEP_LIST_API', 'API'),
       ('task-detail', 'project-detail', 'TASK 상세', 'TASK_DETAIL_API', 'API'),
       ('genx-menu2', NULL, 'GENX 관리자 메뉴2(GENX 시스템 내)', 'GENX_TEST4', 'PAGE'),
       ('workflow', NULL, '워크플로우', 'GENX_APP', 'PAGE'),
       ('work-list', NULL, '작업 목록', 'WORK_LIST', 'PAGE'),
       ('work-list-read', 'work-list', '작업 목록 조회', 'WORK_LIST_API_R', 'API'),
       ('schedule-work', NULL, '예약작업 관리', 'SCHEDULE_WORK_LIST', 'PAGE'),
       ('schedule-work-read', 'schedule-work', '예약작업 목록 조회', 'SCHEDULE_WORK_API_R', 'API'),
       ('bbs-list', NULL, '소통 게시판', 'BBS_LIST', 'PAGE'),
       ('bbs-list-read', 'bbs-list', '게시글 목록 조회', 'BBS_API_R', 'API'),
       ('app-list', NULL, 'APP 관리', 'APP_LIST', 'PAGE'),
       ('app-list-read', 'app-list', 'APP 목록 조회', 'APP_LIST_API_R', 'API'),
       ('app-register', NULL, 'APP 빌더', 'APP_REGISTER', 'PAGE'),
       ('node-list', NULL, '노드관리', 'NODE_LIST', 'PAGE'),
       ('node-list-read', 'node-list', '노드 목록 조회', 'NODE_LIST_API_R', 'API'),
       ('work-node-list', NULL, '노드관리 (워크스페이스 관리자)', 'WORK_NODE_LIST', 'PAGE'),
       ('work-node-list-read', 'work-node-list', '노드 목록 조회 (워크스페이스)', 'WORK_NODE_LIST_API_R', 'API'),
       ('app-mode', NULL, 'APP', 'APP_MODE', 'PAGE');
