-- V17은 spring-batch-core의 schema-mysql.sql(진짜 SEQUENCE가 없는 MySQL을 위해
-- 테이블 + UNIQUE 제약으로 시퀀스를 흉내내는 방식)을 그대로 가져와 BATCH_JOB_SEQ /
-- BATCH_JOB_EXECUTION_SEQ / BATCH_STEP_EXECUTION_SEQ를 일반 테이블로 만들었다.
-- 그런데 Spring Batch 5.x는 MariaDB JDBC 드라이버를 인식하면 DatabaseType을 MYSQL이 아닌
-- MARIADB로 판별해 `SELECT NEXT VALUE FOR BATCH_JOB_SEQ`처럼 진짜 SQL SEQUENCE 문법을 쓰는
-- 인크리멘터(schema-mariadb.sql 참고)를 선택한다. V17의 테이블은 진짜 SEQUENCE가 아니므로
-- "'ebook.BATCH_JOB_SEQ' is not a SEQUENCE" 오류가 발생한다.
-- MariaDB 10.3+는 네이티브 SEQUENCE를 지원하므로, 테이블을 지우고 spring-batch-core가
-- 실제로 기대하는 SEQUENCE 오브젝트로 교체한다.

DROP TABLE BATCH_STEP_EXECUTION_SEQ;
DROP TABLE BATCH_JOB_EXECUTION_SEQ;
DROP TABLE BATCH_JOB_SEQ;

CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775806 INCREMENT BY 1 NOCACHE NOCYCLE ENGINE=InnoDB;
CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775806 INCREMENT BY 1 NOCACHE NOCYCLE ENGINE=InnoDB;
CREATE SEQUENCE BATCH_JOB_SEQ START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775806 INCREMENT BY 1 NOCACHE NOCYCLE ENGINE=InnoDB;
